import Head from "next/head";
import React, { useState } from "react";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [ends, setEnds] = useState([]);

  // add scores for an end
  const addEnd = async (event) => {
    await setEnds(() => {
      event.preventDefault();
      const rileyScore = event.target.riley.value;
      const opponentScore = event.target.opponent.value;

      const updatedEnds = [...ends];
      updatedEnds.push([rileyScore, opponentScore]);

      return updatedEnds;
    });

    // reset the form
    event.target.reset();
  };

  // delete an end
  const deleteEnd = (endNumber) =>
    setEnds(() => {
      const updatedEndState = [...ends];
      updatedEndState.splice(endNumber, 1);
      return updatedEndState;
    });

  // calculate the total running score
  // run on each new end addition, maybe should be state but such is life
  const calculateEndTotal = (index, playerIndex) =>
    [...ends].reduce(
      (total, current, i) =>
        i <= index ? parseInt(total) + parseInt(current[playerIndex]) : total,
      0
    );

  // total ends won by each player
  const calculateEndsWon = (playerIndex) => {
    const otherIndex = playerIndex === 0 ? 1 : 0;
    return [...ends].reduce(
      (total, current) =>
        current[playerIndex] > current[otherIndex] ? total + 1 : total,
      0
    );
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Riley Bowls on Lawns</title>
        <meta
          name="description"
          content="Generated by create next app, bowled by Riley"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0,user-scalable=0"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Riley Bowls on Lawns</h1>

        <table style={{ width: "100%" }}>
          <colgroup>
            <col span="1" style={{ width: "10%" }} />
            <col span="1" style={{ width: "20%" }} />
            <col span="1" style={{ width: "20%" }} />
            <col span="1" style={{ width: "20%" }} />
            <col span="1" style={{ width: "20%" }} />
          </colgroup>

          <thead>
            <tr key={"title"}>
              <th>End</th>
              <th>Riley</th>
              <th>Total</th>
              <th>Opponent</th>
              <th>Total</th>
            </tr>
          </thead>
          <tbody>
            {ends.map((e, i) => (
              <tr key={i}>
                <th>{i + 1}</th>
                <th>{e[0]}</th>
                <th>{calculateEndTotal(i, 0)}</th>
                <th>{e[1]}</th>
                <th>{calculateEndTotal(i, 1)}</th>
                <th>
                  <button onClick={() => deleteEnd(i)}>Delete</button>
                </th>
              </tr>
            ))}
            <tr>
              <th>
                <br />
              </th>
            </tr>
            <tr>
              <th>Ends won:</th>
              <th />
              <th>{calculateEndsWon(0)}</th>
              <th />
              <th>{calculateEndsWon(1)}</th>
            </tr>
          </tbody>
        </table>

        <form id="lawn-bowls-form" onSubmit={addEnd}>
          <div className={styles.form}>
            <span>
              <div className={styles.input}>
                <label htmlFor="riley">Riley:</label>
                <input type="number" id="riley" name="riley" required />
              </div>
              <div className={styles.input}>
                <label htmlFor="opponent">Opponent:</label>
                <input type="number" id="opponent" name="opponent" required />
              </div>
            </span>
            <button type="submit">Finish End</button>
          </div>
        </form>
      </main>

      <footer className={styles.footer}>Powered by Riley</footer>
    </div>
  );
}
